### ISSUE TITLE
Generated assets are all empty

### ISSUE THREAD

**Issue by rhys-vdw** [AdamFrisby/Post-Stack-Converter#1]
Hm, seems to work, but when I save the profiles all look like this:

```yaml
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!114 &11400000
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 0}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: 8e6292b2c06870d4495f009f912b9600, type: 3}
  m_Name: Menu Post-Processing Profile
  m_EditorClassIdentifier: 
  settings:
  - {fileID: 0}
  - {fileID: 0}
  - {fileID: 0}
```

I can get around it by copying each effect, deleting it, then pasting it. Very strange.
